# Generated by Django 5.2.6 on 2025-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_product_image_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Customer', max_length=50),
        ),
    ]
