# Generated by Django 5.2.6 on 2025-10-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(blank=True, to='users.product'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
